In [15]:
import nltk
import numpy as np
import random
import string 
f=open('practraincorpus.txt','r',errors = 'ignore')
raw=f.read()
raw=raw.lower()


f=open('practraincorpus2.txt','r',errors = 'ignore')
raw2=f.read()
raw2=raw2.lower()


In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords
import numpy as np
import numpy.linalg as LA

train_set = [raw, raw2] #Documents
test_set = ["where is riviera held in vit vellore"] #Query
stopWords = stopwords.words('english')

vectorizer = CountVectorizer(stop_words = stopWords)
#print vectorizer
transformer = TfidfTransformer()
#print transformer

trainVectorizerArray = vectorizer.fit_transform(train_set).toarray()
testVectorizerArray = vectorizer.transform(test_set).toarray()
print('Fit Vectorizer to train set', trainVectorizerArray)
print('Transform Vectorizer to test set', testVectorizerArray)
cx = lambda a, b : round(np.inner(a, b)/(LA.norm(a)*LA.norm(b)), 3)

for vector in trainVectorizerArray:
    print('.............')
    print(vector)
    for testV in testVectorizerArray:
        print('....')
        print(testV)
        cosine = cx(vector, testV)
        print('Cosine: ',end='')
        print(cosine)
        print('....')
    print('.............')

transformer.fit(trainVectorizerArray)

print(transformer.transform(trainVectorizerArray).toarray())

transformer.fit(testVectorizerArray)

tfidf = transformer.transform(testVectorizerArray)
print('Tfidf: ',end='')
print(tfidf.todense())


Fit Vectorizer to train set [[2 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
Transform Vectorizer to test set [[0 0 0 ... 0 0 0]]
.............
[2 0 0 ... 0 0 0]
....
[0 0 0 ... 0 0 0]
Cosine: 0.355
....
.............
.............
[1 1 1 ... 1 1 1]
....
[0 0 0 ... 0 0 0]
Cosine: 0.292
....
.............
[[0.02235407 0.         0.         ... 0.         0.         0.        ]
 [0.00716928 0.01007618 0.01007618 ... 0.01007618 0.01007618 0.01007618]]
Tfidf: [[0. 0. 0. ... 0. 0. 0.]]


In [19]:
train_set = [raw, raw2] #Documents
test_set = ["vellore institute of technology is a private deemed university with campuses in vellore, chennai, bhopal and amaravati"] #Query
stopWords = stopwords.words('english')

vectorizer = CountVectorizer(stop_words = stopWords)
#print vectorizer
transformer = TfidfTransformer()
#print transformer

trainVectorizerArray = vectorizer.fit_transform(train_set).toarray()
testVectorizerArray = vectorizer.transform(test_set).toarray()
print('Fit Vectorizer to train set', trainVectorizerArray)
print('Transform Vectorizer to test set', testVectorizerArray)
cx = lambda a, b : round(np.inner(a, b)/(LA.norm(a)*LA.norm(b)), 3)

for vector in trainVectorizerArray:
    print('.............')
    print(vector)
    for testV in testVectorizerArray:
        print('....')
        print(testV)
        cosine = cx(vector, testV)
        print(cosine)
        print('....')
    print('.............')

transformer.fit(trainVectorizerArray)

print(transformer.transform(trainVectorizerArray).toarray())

transformer.fit(testVectorizerArray)

tfidf = transformer.transform(testVectorizerArray)
print(tfidf.todense())


Fit Vectorizer to train set [[2 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
Transform Vectorizer to test set [[0 0 0 ... 0 0 0]]
.............
[2 0 0 ... 0 0 0]
....
[0 0 0 ... 0 0 0]
0.062
....
.............
.............
[1 1 1 ... 1 1 1]
....
[0 0 0 ... 0 0 0]
0.414
....
.............
[[0.02235407 0.         0.         ... 0.         0.         0.        ]
 [0.00716928 0.01007618 0.01007618 ... 0.01007618 0.01007618 0.01007618]]
[[0. 0. 0. ... 0. 0. 0.]]


In [30]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances

corpus = [
'where is riviera held in vit vellore',raw,raw2]

vectorizer = CountVectorizer()
features = vectorizer.fit_transform(corpus).todense() 
print( vectorizer.vocabulary_ )

for f in features:
    print( euclidean_distances(features[0], f) )

{'where': 1278, 'is': 599, 'riviera': 965, 'held': 530, 'in': 564, 'vit': 1257, 'vellore': 1237, 'festival': 452, 'from': 490, 'wikipedia': 1289, 'the': 1166, 'free': 488, 'encyclopedia': 409, 'jump': 611, 'to': 1190, 'navigationjump': 755, 'search': 1011, 'university': 1218, 'vitrivieradp': 1261, 'png': 859, 'logo': 673, 'of': 784, 'genre': 504, 'sports': 1083, 'and': 118, 'cultural': 321, 'carnival': 219, 'location': 671, 'india': 571, 'founded': 483, '2002': 26, 'attendance': 152, '30': 53, '000': 0, 'footfall': 478, '500': 60, 'colleges': 267, 'filing': 461, 'status': 1102, 'student': 1112, 'run': 974, 'non': 773, 'profit': 887, 'organization': 805, 'sponsor': 1079, 'institute': 585, 'technology': 1152, 'website': 1271, 'www': 1304, 'vitriviera': 1260, 'com': 271, 'annual': 124, 'international': 594, 'it': 604, 'an': 116, 'day': 330, 'event': 423, 'that': 1165, 'consists': 293, 'competitions': 281, 'social': 1061, 'events': 424, 'along': 108, 'with': 1294, 'concerts': 286, '2016': 

In [31]:
#therefore query matches doc1 more